### PR TITLE
fix updating from 1.x to 2.y when y > 0

### PR DESCRIPTION
**Pull request by RekGRpth**
If updating from 1.x to 2.y when y > 0 then following error is occurred
```sql
alter extension diskquota update;
ERROR:  could not access file "$libdir/diskquota-2.0.so": No such file or directory
```
because there is no other versions of .so-files except current one.
Solution is making symlinks for every old versions of .so-files to current one.

### CODE REVIEW

**Comment by Stolb27** [comment]
I've tested your solution:

```
 1175  rm -rf build/
 1176  mkdir build
 1177  cd build/
 1180  export PATH=/home/givi/projects/cmake-3.20.0-linux-x86_64/bin/:$PATH
 1181  cmake ..
 1182  cmake .. -DDISKQUOTA_DDL_CHANGE_CHECK=OFF
 1183  DESTDIR=/tmp/dq/ make install
```

symlink from 2.0 to 2.1 wasn't created:

```
givi@samsung-ivanov:~/projects/diskquota/build$ ls -l /tmp/dq/home/givi/builds/6.22.1_arenadata41/lib/postgresql/
total 964
-rw-r--r-- 1 givi givi 981824 Mar  9 12:45 diskquota-2.1.so
```

**Comment by RekGRpth** [comment]
hm...

> symlink from 2.0 to 2.1 was

created in place as DESTDIR is empty

**Comment by RekGRpth** [comment]
> symlink from 2.0 to 2.1 wasn't created

fixed

**Comment by Stolb27** [comment]
@RekGRpth, please rebase this branch to actual gpdb branch state

**Comment by RekGRpth** [comment]
> rebase this branch to actual gpdb branch state

done, thank You for notification

**Comment by Stolb27** [comment]
@deart2k, ready to build

**Review by Stolb27 — APPROVED** [review]
This patch was successfully tested by the bundle team

**Pull request merged**
