### PR TITLE
ADBDEV-3552 2.2.0 sync

### PR DESCRIPTION
**Pull request by deart2k**

### CODE REVIEW

**Comment by RekGRpth** [comment]
I suggest firstly use https://github.com/arenadata/diskquota/pull/12

**Review by RekGRpth — APPROVED** [review]

**Comment by Stolb27** [comment]
> I suggest firstly use https://github.com/arenadata/diskquota/pull/12

@RekGRpth, can you describe why? #12 is tested yet by bundle team. And we will be able to test #12 with 2.2.0 too.

**Comment by RekGRpth** [comment]
> can you describe why?

because 2.1 and 2.2 can not update from 1.x until apply it

**Comment by Stolb27** [comment]
> because 2.1 and 2.2 can not update from 1.x until apply it

but 2.1 was already merged. What's changed if 2.2 will be merged too? But of course, we can't release 2.2 (as 2.1) without #12

**Comment by RekGRpth** [comment]
> but 2.1 was already merged

I suggest PR to gpdb branch, not to 2.1

**Comment by RekGRpth** [comment]
I just suggest to make release 2.1 with https://github.com/arenadata/diskquota/pull/12 first

**Pull request merged**
