### PR TITLE
Split update SQL statement for diskquota.table_size

### PR DESCRIPTION
**Pull request by red1452**
This is cherry-pick from [commit 4a73b1975b745792d2cf048721e643298d4f3449](https://github.com/greenplum-db/diskquota/pull/325)

 ## Problem
 If the number of entries needed to be updated in diskquota.table_size is too many, the size of StringBuffer will exceed 1GB and raise an error `Cannot enlarge string buffer containing 1073741807 bytes by 20 more bytes.`.
 
 ## Solution
 We should limit the number of entries in update statement to 1000000 every times to ensure the string buffer size does not exceed 1GB.

### CODE REVIEW

**Comment by RekGRpth** [comment]
Is it possible to test this?

**Comment by RekGRpth** [comment]
Why is the github action successful in upstream, but not in our fork?

**Review by RekGRpth — APPROVED** [review]
It is pure cherry-pick.

**Comment by red1452** [comment]
This patch will be merged by [sync 2.2.1](https://github.com/arenadata/diskquota/pull/18).

**Pull request closed without merging**
